name: "Build macOS CLI (Ubuntu + DarlingHQ)"

on:
  workflow_dispatch:

jobs:
  darling-nuitka:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4

    - name: 🛠️ Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip cmake clang bison flex libfuse-dev libudev-dev pkg-config

    - name: 🍏 Install Darling (v0.1.20260222)
      run: |
        wget https://github.com/darlinghq/darling/releases/download/v0.1.20260222/debs_20260222.zip
        unzip debs_20260222.zip
        
        # 🔴 FIX: Pointing to the 'debs' folder created by unzip
        sudo apt install -y ./debs/*.deb || echo "Installation had issues, but trying to continue..."

    - name: 🚀 Run Darling Shell
      run: |
        # This will likely fail because darling-dkms is not in the zip
        darling shell uname -a
